### ISSUE TITLE
Colibri imx6Dl - DDR size

### ISSUE THREAD

**Issue by agherzan** [resin-os/resin-toradex#19]
@agherzan commented on [Mon Jul 04 2016](https://github.com/resin-os/resin-ts/issues/27)

There is a bug on the Colibri imx6DL that results in only seeing half of the RAM memory available on the hardware. There is a fix in u-boot for this (a patch). I will update this task after I have more information from Toradex (Brandon).

**Comment by telphan** [comment]
Fixed here: https://github.com/resin-os/resin-toradex/pull/10
